// packages/ui/solid-ui-geo/src/components/Map/Map.tsx
//
// Copyright 2025 DXOS.org
//

import 'leaflet/dist/leaflet.css';
import L, { type ControlPosition, type LatLngLiteral, latLngBounds } from 'leaflet';
import {
  type Accessor,
  type JSX,
  type Setter,
  Show,
  createContext,
  createEffect,
  createSignal,
  onCleanup,
  onMount,
  useContext,
} from 'solid-js';

import { type GeoMarker } from '../../types';
import { ActionControls, type ControlProps, ZoomControls, controlPositions } from '../Toolbar';

// TODO(burdon): Guess initial location.

const defaults = {
  center: { lat: 51, lng: 0 } as L.LatLngLiteral,
  zoom: 4,
} as const;

//
// Controller
//

export type MapController = {
  setCenter: (center: LatLngLiteral, zoom?: number) => void;
  setZoom: (cb: (zoom: number) => number) => void;
};

//
// Context
//

type MapContextValue = {
  map: Accessor<L.Map | null>;
  attention: Accessor<boolean>;
  setAttention: Setter<boolean>;
  onChange?: (ev: { center: LatLngLiteral; zoom: number }) => void;
};

const MapContext = createContext<MapContextValue>();

const useMapContext = (displayName: string) => {
  const context = useContext(MapContext);
  if (!context) {
    throw new Error(`${displayName} must be used within Map.Root`);
  }

  return context;
};

//
// Root
//

type MapRootProps = {
  ref?: (controller: MapController) => void;
  children: JSX.Element;
  class?: string;
  scrollWheelZoom?: boolean;
  doubleClickZoom?: boolean;
  touchZoom?: boolean;
  center?: LatLngLiteral;
  zoom?: number;
  onChange?: (ev: { center: LatLngLiteral; zoom: number }) => void;
};

/**
 * https://leafletjs.com/reference.html#map
 */

const MapRoot = (props: MapRootProps) => {
  let mapContainer: HTMLDivElement | undefined;
  const [map, setMap] = createSignal<L.Map | null>(null);
  const [attention, setAttention] = createSignal(false);

  onMount(() => {
    if (!mapContainer) return;

    const leafletMap = L.map(mapContainer, {
      center: props.center ?? defaults.center,
      zoom: props.zoom ?? defaults.zoom,
      attributionControl: false,
      zoomControl: false,
      scrollWheelZoom: props.scrollWheelZoom ?? true,
      doubleClickZoom: props.doubleClickZoom ?? true,
      touchZoom: props.touchZoom ?? true,
    });

    setMap(leafletMap);

    // Set up controller
    if (props.ref) {
      props.ref({
        setCenter: (center: LatLngLiteral, zoom?: number) => {
          leafletMap.setView(center, zoom);
        },
        setZoom: (cb: (zoom: number) => number) => {
          leafletMap.setZoom(cb(leafletMap.getZoom()));
        },
      });
    }

    onCleanup(() => {
      leafletMap.remove();
    });
  });

  // Enable/disable scroll wheel zoom based on attention
  createEffect(() => {
    const leafletMap = map();
    if (!leafletMap) return;

    if (attention()) {
      leafletMap.scrollWheelZoom.enable();
    } else {
      leafletMap.scrollWheelZoom.disable();
    }
  });

  return (
    <MapContext.Provider value={{ map, attention, setAttention, onChange: props.onChange }}>
      <div
        ref={mapContainer}
        class={`group relative grid h-full w-full bg-gray-100 dark:bg-gray-900 ${props.class ?? ''}`}
        style={{ 'z-index': '0' }}
      />
      <Show when={map()}>{props.children}</Show>
    </MapContext.Provider>
  );
};

//
// Tiles
//

const MapTiles = () => {
  const { map, onChange, attention } = useMapContext(MapTiles.name);
  let tileLayer: L.TileLayer | null = null;

  createEffect(() => {
    const leafletMap = map();
    if (!leafletMap) return;

    const att = attention();
    tileLayer = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      detectRetina: true,
      keepBuffer: 4,
      className: `dark:grayscale dark:invert ${att ? '' : 'opacity-80'}`,
    });

    tileLayer.addTo(leafletMap);

    // Set up event listeners
    leafletMap.on('zoomstart', (ev) => {
      onChange?.({
        center: ev.target.getCenter(),
        zoom: ev.target.getZoom(),
      });
    });

    onCleanup(() => {
      if (tileLayer) {
        tileLayer.remove();
        tileLayer = null;
      }
    });
  });

  // Update tile layer class when attention changes
  createEffect(() => {
    const att = attention();
    if (tileLayer) {
      const container = tileLayer.getContainer();
      if (container) {
        container.className = `dark:grayscale dark:invert ${att ? '' : 'opacity-80'}`;
      }
    }
  });

  return null;
};

//
// Markers
//

type MapMarkersProps = {
  markers?: Accessor<GeoMarker[]>;
};

const MapMarkers = (props: MapMarkersProps) => {
  const { map } = useMapContext(MapMarkers.name);
  const leafletMarkers: L.Marker[] = [];
  let lastMarkerIds = new Set<string>();

  // Clean up all markers when component unmounts
  onCleanup(() => {
    leafletMarkers.forEach((marker) => marker.remove());
    leafletMarkers.length = 0;
  });

  createEffect(() => {
    const leafletMap = map();
    if (!leafletMap) return;

    const markerList = props.markers?.() ?? [];
    const currentIds = new Set(markerList.map((m) => m.id));

    // Skip if the markers haven't actually changed
    if (
      currentIds.size === lastMarkerIds.size &&
      [...currentIds].every((id) => lastMarkerIds.has(id)) &&
      leafletMarkers.length > 0
    ) {
      return;
    }

    // Clear existing markers
    leafletMarkers.forEach((marker) => marker.remove());
    leafletMarkers.length = 0;
    lastMarkerIds = currentIds;

    if (markerList.length > 0) {
      const bounds = latLngBounds(markerList.map((marker) => marker.location));
      leafletMap.fitBounds(bounds);

      // Add new markers
      markerList.forEach(({ title, location }) => {
        const marker = L.marker(location, {
          icon: new L.Icon({
            iconUrl: 'https://dxos.network/marker-icon.png',
            iconRetinaUrl: 'https://dxos.network/marker-icon-2x.png',
            shadowUrl: 'https://dxos.network/marker-shadow.png',
            iconSize: [25, 41],
            iconAnchor: [12, 41],
            popupAnchor: [1, -34],
            shadowSize: [41, 41],
          }),
        });

        if (title) {
          marker.bindPopup(title);
        }

        marker.addTo(leafletMap);
        leafletMarkers.push(marker);
      });
    } else {
      leafletMap.setView(defaults.center, defaults.zoom);
    }
  });

  return null;
};

//
// Controls
//

const CustomControl = (props: { children: JSX.Element; position: ControlPosition }) => {
  const { map: mapAccessor } = useMapContext(CustomControl.name);
  let controlContainer: HTMLDivElement | undefined;

  createEffect(() => {
    const map = mapAccessor();
    if (!map || !controlContainer) return;

    const Control = L.Control.extend({
      onAdd: () => {
        const container = L.DomUtil.create('div', `${controlPositions[props.position]} m-0!`);
        L.DomEvent.disableClickPropagation(container);
        L.DomEvent.disableScrollPropagation(container);

        if (controlContainer) {
          container.appendChild(controlContainer);
        }

        return container;
      },
    });

    const control = new Control({ position: props.position });
    control.addTo(map);

    onCleanup(() => {
      control.remove();
    });
  });

  return (
    <div ref={controlContainer} style={{ display: 'contents' }}>
      {props.children}
    </div>
  );
};

type MapControlProps = { position?: ControlPosition } & Pick<ControlProps, 'onAction'>;

const MapZoom = (props: MapControlProps) => (
  <CustomControl position={props.position ?? 'bottomleft'}>
    <ZoomControls onAction={props.onAction} />
  </CustomControl>
);

const MapAction = (props: MapControlProps) => (
  <CustomControl position={props.position ?? 'bottomright'}>
    <ActionControls onAction={props.onAction} />
  </CustomControl>
);

//
// Map
//

export const Map = {
  Root: MapRoot,
  Tiles: MapTiles,
  Markers: MapMarkers,
  Zoom: MapZoom,
  Action: MapAction,
};

export { type MapRootProps, type MapMarkersProps, type MapControlProps };

// packages/ui/react-ui-geo/src/components/Map/Map.tsx
//
// Copyright 2023 DXOS.org
//

// eslint-disable-next-line no-restricted-imports
import 'leaflet/dist/leaflet.css';

import L, { Control, DomEvent, DomUtil, latLngBounds, type ControlPosition, type LatLngExpression } from 'leaflet';
import React, { forwardRef, useEffect, useImperativeHandle, type PropsWithChildren } from 'react';
import { createRoot } from 'react-dom/client';
import type { MapContainerProps } from 'react-leaflet';
import { MapContainer, Marker, Popup, TileLayer, useMap } from 'react-leaflet';
import { useResizeDetector } from 'react-resize-detector';

import { debounce } from '@dxos/async';
import { ThemeProvider, Tooltip, type ThemedClassName } from '@dxos/react-ui';
import { defaultTx, mx } from '@dxos/react-ui-theme';

import { ActionControls, controlPositions, ZoomControls, type ControlProps } from '../Toolbar';
import { type MapCanvasProps } from '../types';

// TODO(burdon): Explore plugins: https://www.npmjs.com/search?q=keywords%3Areact-leaflet-v4
// TODO(burdon): react-leaflet v5 is not compatible with react 18.

const defaults = {
  // TODO(burdon): Guess location.
  center: { lat: 51, lng: 0 } as L.LatLngExpression,
  zoom: 4,
};

//
// Root
//

type MapRootProps = ThemedClassName<MapContainerProps>;

// https://react-leaflet.js.org/docs/api-map
const MapRoot = ({ classNames, center = defaults.center, zoom = defaults.zoom, ...props }: MapRootProps) => {
  return (
    <MapContainer
      className={mx('relative grid grow bg-baseSurface', classNames)}
      attributionControl={false}
      // TODO(burdon): Only if attention.
      scrollWheelZoom={true}
      zoomControl={false}
      center={center}
      zoom={zoom}
      {...props}
    />
  );
};

//
// Control
//

// TODO(burdon): Normalize with Globe.
type MapController = {
  setCenter: (center: LatLngExpression, zoom?: number) => void;
  setZoom: (cb: (zoom: number) => number) => void;
};

const MapCanvas = forwardRef<MapController, MapCanvasProps>(({ markers, center, zoom, onChange }, forwardedRef) => {
  const { ref, width, height } = useResizeDetector({ refreshRate: 200 });
  const map = useMap();

  useImperativeHandle(
    forwardedRef,
    () => ({
      setCenter: (center: LatLngExpression, zoom?: number) => {
        map.setView(center, zoom);
      },
      setZoom: (cb) => {
        map.setZoom(cb(map.getZoom()));
      },
    }),
    [map],
  );

  // Resize.
  useEffect(() => {
    if (width && height) {
      map.invalidateSize();
    }
  }, [width, height]);

  // Position.
  useEffect(() => {
    if (center) {
      map.setView(center, zoom);
    } else if (zoom !== undefined) {
      map.setZoom(zoom);
    }
  }, [center, zoom]);

  // Events.
  useEffect(() => {
    const handler = debounce(() => {
      onChange?.({ center: map.getCenter(), zoom: map.getZoom() });
    }, 100);
    map.on('move', handler);
    map.on('zoom', handler);
    return () => {
      map.off('move', handler);
      map.off('zoom', handler);
    };
  }, [map, onChange]);

  // Set the viewport around the markers, or show the whole world map if `markers` is empty.
  useEffect(() => {
    if (markers.length > 0) {
      const bounds = latLngBounds(markers.map((marker) => marker.location));
      map.fitBounds(bounds);
    } else {
      map.setView(defaults.center, defaults.zoom);
    }
  }, [markers]);

  return (
    <div ref={ref} className='flex w-full h-full overflow-hidden bg-baseSurface'>
      {/* Map tiles. */}
      <TileLayer
        className='dark:filter dark:grayscale dark:invert'
        url='https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
      />

      {/* Markers. */}
      {markers?.map(({ id, title, location: { lat, lng } }) => {
        return (
          <Marker
            key={id}
            position={{ lat, lng }}
            icon={
              // TODO(burdon): Create custom icon from bundled assets.
              new L.Icon({
                iconUrl: 'https://dxos.network/marker-icon.png',
                iconRetinaUrl: 'https://dxos.network/marker-icon-2x.png',
                shadowUrl: 'https://dxos.network/marker-shadow.png',
                iconSize: [25, 41],
                iconAnchor: [12, 41],
                popupAnchor: [1, -34],
                shadowSize: [41, 41],
              })
            }
          >
            {title && <Popup>{title}</Popup>}
          </Marker>
        );
      })}
    </div>
  );
});

//
// Controls
// Integrates with Leaflet custom controls.
//

const CustomControl = ({
  position,
  children,
}: PropsWithChildren<{
  position: ControlPosition;
}>) => {
  const map = useMap();

  useEffect(() => {
    const control = new Control({ position });
    control.onAdd = () => {
      const container = DomUtil.create('div', mx('!m-0', controlPositions[position]));
      DomEvent.disableClickPropagation(container);
      DomEvent.disableScrollPropagation(container);

      const root = createRoot(container);
      root.render(
        <ThemeProvider tx={defaultTx}>
          <Tooltip.Provider>{children}</Tooltip.Provider>
        </ThemeProvider>,
      );

      return container;
    };

    control.addTo(map);
    return () => {
      control.remove();
    };
  }, [map, position, children]);

  return null;
};

type MapControlProps = { position?: ControlPosition } & Pick<ControlProps, 'onAction'>;

//
// Map
//

export const Map = {
  Root: MapRoot,
  Canvas: MapCanvas,
  Zoom: ({ onAction, position = 'bottomleft', ...props }: MapControlProps) => (
    <CustomControl position={position} {...props}>
      <ZoomControls onAction={onAction} />
    </CustomControl>
  ),
  Action: ({ onAction, position = 'bottomright', ...props }: MapControlProps) => (
    <CustomControl position={position} {...props}>
      <ActionControls onAction={onAction} />
    </CustomControl>
  ),
};

export { type MapCanvasProps, type MapController };
