// packages/plugins/plugin-map-solid/src/components/Map/MapControl.tsx
//
// Copyright 2025 DXOS.org
//

import { createSignal } from 'solid-js';

import { type ControlProps, Map, type MapController, type LatLngLiteral, useMapZoomHandler } from '@dxos/solid-ui-geo';

import { type GeoControlProps } from '../types';

export type MapControlProps = GeoControlProps & {
  onChange?: (ev: { center: LatLngLiteral; zoom: number }) => void;
};

export const MapControl = (props: MapControlProps) => {
  const [controller, setController] = createSignal<MapController | null>(null);
  const handleZoomAction = useMapZoomHandler(controller());

  const handleAction: ControlProps['onAction'] = (action) => {
    switch (action) {
      case 'toggle': {
        props.onToggle?.();
        break;
      }
    }
  };

  return (
    <Map.Root ref={setController} class={props.class} center={props.center} zoom={props.zoom} onChange={props.onChange}>
      <Map.Tiles />
      <Map.Markers markers={props.markers} />
      {props.onToggle && <Map.Action onAction={handleAction} />}
      <Map.Zoom onAction={handleZoomAction} />
    </Map.Root>
  );
};

// packages/plugins/plugin-map/src/components/Map/MapControl.tsx
//
// Copyright 2024 DXOS.org
//

import React, { useState } from 'react';

import { type ControlProps, Map, type MapController, type MapRootProps, useMapZoomHandler } from '@dxos/react-ui-geo';

import { type GeoControlProps } from '../types';

export type MapControlProps = GeoControlProps & MapRootProps;

export const MapControl = ({ classNames, center, zoom, markers, selected, onToggle, onChange }: MapControlProps) => {
  const [controller, setController] = useState<MapController | null>(null);
  const handleZoomAction = useMapZoomHandler(controller);

  const handleAction: ControlProps['onAction'] = (action) => {
    switch (action) {
      case 'toggle': {
        onToggle?.();
        break;
      }
    }
  };

  return (
    <Map.Root ref={setController} classNames={classNames} center={center} zoom={zoom} onChange={onChange}>
      <Map.Tiles />
      <Map.Markers markers={markers} selected={selected} />
      {onToggle && <Map.Action onAction={handleAction} />}
      <Map.Zoom onAction={handleZoomAction} />
    </Map.Root>
  );
};
