// packages/sdk/app-framework/src/react/useCapabilities.ts
//
// Copyright 2025 DXOS.org
//

import { computed } from '@preact/signals-core';
import { useMemo } from 'react';

import { usePluginManager } from './PluginManagerProvider';
import { type InterfaceDef } from '../core';

/**
 * Hook to request capabilities from the plugin context.
 * @returns An array of capabilities.
 */
export const useCapabilities = <T, U extends T = T>(
  interfaceDef: InterfaceDef<T>,
  filter?: (capability: T) => capability is U,
) => {
  const manager = usePluginManager();
  const signal = useMemo(
    () => computed(() => manager.context.requestCapabilities(interfaceDef, filter)),
    [interfaceDef, filter],
  );
  return signal.value;
};

/**
 * Hook to request a capability from the plugin context.
 * @returns The capability.
 * @throws If no capability is found.
 */
export const useCapability = <T, U extends T = T>(
  interfaceDef: InterfaceDef<T>,
  filter?: (capability: T) => capability is U,
) => {
  const manager = usePluginManager();
  const signal = useMemo(
    () => computed(() => manager.context.requestCapability(interfaceDef, filter)),
    [interfaceDef, filter],
  );
  return signal.value;
};

// packages/sdk/app-solid/src/useCapabilities.ts
//
// Copyright 2025 DXOS.org
//

import { type Accessor } from 'solid-js';

import { type Capability } from '@dxos/app-framework';
import { useAtomValue } from '@dxos/effect-atom-solid';
import { invariant } from '@dxos/invariant';

import { usePluginManager } from './usePluginManager';

/**
 * Hook to request capabilities from the plugin context.
 * @returns An array of capabilities.
 */
export const useCapabilities = <T>(interfaceDef: Capability.InterfaceDef<T>): Accessor<T[]> => {
  const manager = usePluginManager();
  return useAtomValue(manager.capabilities.atom(interfaceDef));
};

/**
 * Hook to request a capability from the plugin context.
 * @returns The capability.
 * @throws If no capability is found.
 */
export const useCapability = <T>(interfaceDef: Capability.InterfaceDef<T>): Accessor<T> => {
  const capabilities = useCapabilities(interfaceDef);
  return (() => {
    const caps = capabilities();
    invariant(caps.length > 0, `No capability found for ${interfaceDef.identifier}`);
    return caps[0];
  }) as Accessor<T>;
};
