// packages/core/echo/echo-solid/src/useQuery.ts
//
// Copyright 2025 DXOS.org
//

import { type Accessor, createEffect, createMemo, createSignal, onCleanup } from 'solid-js';

import { type Database, type Entity, Filter, Query } from '@dxos/echo';

const EMPTY_ARRAY: never[] = [];

type MaybeAccessor<T> = T | Accessor<T>;

/**
 * Create a reactive query subscription.
 * Accepts either values or accessors for resource and query/filter.
 *
 * @param resource - The database or queryable resource (can be reactive)
 * @param queryOrFilter - The query or filter to apply (can be reactive)
 * @returns An accessor that returns the current query results
 */
export const useQuery = <T extends Entity.Any = Entity.Any>(
  resource: MaybeAccessor<Database.Queryable | undefined>,
  queryOrFilter: MaybeAccessor<Query.Any | Filter.Any>,
): Accessor<T[]> => {
  // Derive the normalized query from the input
  const query = createMemo(() => {
    const resolved = typeof queryOrFilter === 'function' ? queryOrFilter() : queryOrFilter;
    return Filter.is(resolved) ? Query.select(resolved) : resolved;
  });

  // Derive the query result object reactively
  const queryResult = createMemo(() => {
    const q = query();
    const resolvedResource = typeof resource === 'function' ? resource() : resource;
    return resolvedResource?.query(q);
  });

  // Store the current results in a signal
  const [objects, setObjects] = createSignal<T[]>(EMPTY_ARRAY as T[]);

  // Subscribe to query result changes
  createEffect(() => {
    const result = queryResult();
    if (!result) {
      // Keep previous value during transitions to prevent flickering
      return;
    }

    // Subscribe with immediate fire to get initial results
    const unsubscribe = result.subscribe(
      () => {
        setObjects(() => result.results as T[]);
      },
      { fire: true },
    );

    onCleanup(unsubscribe);
  });

  return objects;
};

// packages/core/echo/echo-react/src/useQuery.ts
//
// Copyright 2022 DXOS.org
//

import { useMemo, useSyncExternalStore } from 'react';

import { type Database, type Entity, Filter, Query } from '@dxos/echo';

const EMPTY_ARRAY: never[] = [];

const noop = () => {};

interface UseQueryFn {
  <Q extends Query.Any, O extends Entity.Entity<Query.Type<Q>> = Entity.Entity<Query.Type<Q>>>(
    resource: Database.Queryable | undefined,
    query: Q,
  ): O[];

  <F extends Filter.Any, O extends Entity.Entity<Filter.Type<F>> = Entity.Entity<Filter.Type<F>>>(
    resource: Database.Queryable | undefined,
    filter: F,
  ): O[];
}

/**
 * Create subscription.
 */
export const useQuery: UseQueryFn = (
  resource: Database.Queryable | undefined,
  queryOrFilter: Query.Any | Filter.Any,
): Entity.Any[] => {
  const query = Filter.is(queryOrFilter) ? Query.select(queryOrFilter) : queryOrFilter;

  const { getObjects, subscribe } = useMemo(() => {
    let queryResult = undefined;
    if (resource) {
      queryResult = resource.query(query);
    }

    let subscribed = false;
    return {
      getObjects: () => (subscribed && queryResult ? queryResult.results : EMPTY_ARRAY),
      subscribe: (cb: () => void) => {
        subscribed = true;
        const unsubscribe = queryResult?.subscribe(cb) ?? noop;
        return () => {
          unsubscribe?.();
          subscribed = false;
        };
      },
    };
  }, [resource, JSON.stringify(query.ast)]);

  // https://beta.reactjs.org/reference/react/useSyncExternalStore
  // NOTE: This hook will resubscribe whenever the callback passed to the first argument changes; make sure it is stable.
  const objects = useSyncExternalStore<Entity.Any[]>(subscribe, getObjects);
  return objects;
};
