// packages/plugins/plugin-map-solid/src/components/Map/MapControl.tsx
//
// Copyright 2025 DXOS.org
//

import { createSignal } from 'solid-js';

import { type ControlProps, Map, type MapController, type LatLngLiteral, useMapZoomHandler } from '@dxos/solid-ui-geo';

import { type GeoControlProps } from '../types';

export type MapControlProps = GeoControlProps & {
  onChange?: (ev: { center: LatLngLiteral; zoom: number }) => void;
};

export const MapControl = (props: MapControlProps) => {
  const [controller, setController] = createSignal<MapController | null>(null);
  const handleZoomAction = useMapZoomHandler(controller());

  const handleAction: ControlProps['onAction'] = (action) => {
    switch (action) {
      case 'toggle': {
        props.onToggle?.();
        break;
      }
    }
  };

  return (
    <Map.Root ref={setController} class={props.class} center={props.center} zoom={props.zoom} onChange={props.onChange}>
      <Map.Tiles />
      <Map.Markers markers={props.markers} />
      {props.onToggle && <Map.Action onAction={handleAction} />}
      <Map.Zoom onAction={handleZoomAction} />
    </Map.Root>
  );
};

// packages/plugins/experimental/plugin-map/src/components/MapControl.tsx
//
// Copyright 2024 DXOS.org
//

import React from 'react';

import { Map, type MapCanvasProps } from './Map';

export type MapControlProps = MapCanvasProps & { onToggle?: () => void };

export const MapControl = ({ classNames, markers, center, zoom, onToggle, onChange }: MapControlProps) => {
  return (
    <Map.Root classNames={classNames}>
      <Map.Canvas markers={markers} center={center} zoom={zoom} onChange={onChange} />
      <Map.ActionControls onAction={onToggle} />
      <Map.ZoomControls />
    </Map.Root>
  );
};
