// packages/sdk/app-solid/src/useIntentResolver.ts
//
// Copyright 2025 DXOS.org
//

import { createEffect, onCleanup } from 'solid-js';

import { type AnyIntentResolver, Common } from '@dxos/app-framework';

import { usePluginManager } from './usePluginManager';

export const useIntentResolver = (module: string, resolver: AnyIntentResolver) => {
  const manager = usePluginManager();

  createEffect(() => {
    manager.context.contributeCapability({
      module,
      interface: Common.Capability.IntentResolver,
      implementation: resolver,
    });

    onCleanup(() => {
      manager.context.removeCapability(Common.Capability.IntentResolver, resolver);
    });
  });
};

// packages/sdk/app-framework/src/react/useIntentResolver.ts
//
// Copyright 2023 DXOS.org
//

import { useEffect } from 'react';

import * as Common from '../common';
import { type AnyIntentResolver } from '../plugin-intent';
import { usePluginManager } from '../react';

export const useIntentResolver = (module: string, resolver: AnyIntentResolver) => {
  const manager = usePluginManager();
  useEffect(() => {
    manager.context.contributeCapability({
      module,
      interface: Common.Capability.IntentResolver,
      implementation: resolver,
    });

    return () => manager.context.removeCapability(Common.Capability.IntentResolver, resolver);
  }, [module, resolver]);
};
