// packages/sdk/app-solid/src/useOperationResolver.ts
//
// Copyright 2025 DXOS.org
//

import { createEffect, onCleanup } from 'solid-js';

import { Common } from '@dxos/app-framework';
import { type OperationResolver } from '@dxos/operation';

import { usePluginManager } from './usePluginManager';

export const useOperationResolver = (module: string, resolver: OperationResolver.OperationResolver) => {
  const manager = usePluginManager();

  createEffect(() => {
    const implementation = [resolver];

    manager.capabilities.contribute({
      module,
      interface: Common.Capability.OperationResolver,
      implementation,
    });

    onCleanup(() => {
      manager.capabilities.remove(Common.Capability.OperationResolver, implementation);
    });
  });
};

// packages/sdk/app-framework/src/react/useOperationResolver.ts
//
// Copyright 2025 DXOS.org
//

import { useEffect, useMemo } from 'react';

import * as Common from '../common';
import { usePluginManager } from '../react';

/**
 * Hook to dynamically register an operation resolver (handler) within a React component.
 * The resolver is added when the component mounts and removed when it unmounts.
 *
 * @example
 * ```tsx
 * const scrollHandler = useMemo(() => OperationResolver.make({
 *   operation: LayoutOperation.ScrollIntoView,
 *   handler: (input) => Effect.sync(() => {
 *     // Handle scroll
 *   }),
 * }), [deps]);
 *
 * useOperationResolver(meta.id, scrollHandler);
 * ```
 */
export const useOperationResolver = (module: string, resolver: Common.Capability.OperationResolver) => {
  const manager = usePluginManager();
  // Wrap single resolver in array as the capability expects an array.
  const resolverArray = useMemo(() => [resolver], [resolver]);

  useEffect(() => {
    manager.capabilities.contribute({
      module,
      interface: Common.Capability.OperationResolver,
      implementation: resolverArray,
    });

    return () => manager.capabilities.remove(Common.Capability.OperationResolver, resolverArray);
  }, [module, resolverArray]);
};
