// packages/core/echo/echo-react/src/useSchema.ts
//
// Copyright 2025 DXOS.org
//

import * as Effect from 'effect/Effect';
import { useMemo, useSyncExternalStore } from 'react';

import { type Database, Type } from '@dxos/echo';

/**
 * Subscribe to and retrieve schema changes from a space's schema registry.
 */
export const useSchema = (db?: Database.Database, typename?: string): Type.Type | undefined => {
  const { subscribe, getSchema } = useMemo(() => {
    if (!typename || !db) {
      return {
        subscribe: () => () => {},
        getSchema: (): Type.Type | undefined => undefined,
      };
    }

    let currentSchema = Effect.runSync(db.graph.registry.listTypes()).find((t) => Type.getTypename(t) === typename) as T | undefined;

    return {
      subscribe: (onStoreChange: () => void) => {
        const unsubscribe = db.graph.registry.changed.on(() => {
          currentSchema = Effect.runSync(db.graph.registry.listTypes()).find((t) => Type.getTypename(t) === typename) as T | undefined;
          onStoreChange();
        });

        return unsubscribe;
      },
      getSchema: () => currentSchema,
    };
  }, [typename, db]);

  return useSyncExternalStore(subscribe, getSchema);
};

// packages/core/echo/echo-solid/src/useSchema.ts
//
// Copyright 2025 DXOS.org
//

import * as Effect from 'effect/Effect';
import { type Accessor, createEffect, createMemo, createSignal, onCleanup } from 'solid-js';

import { type Database, Type } from '@dxos/echo';

type MaybeAccessor<T> = T | Accessor<T>;

/**
 * Subscribe to and retrieve schema changes from a database's schema registry.
 * Accepts either values or accessors for db and typename.
 *
 * @param db - The database instance (can be reactive)
 * @param typename - The schema typename to query (can be reactive)
 * @returns An accessor that returns the current schema or undefined
 */
export const useSchema = (
  db?: MaybeAccessor<Database.Database | undefined>,
  typename?: MaybeAccessor<string | undefined>,
): Accessor<T | undefined> => {
  // Derive resolved values reactively.
  const resolved = createMemo(() => {
    const resolvedDb = typeof db === 'function' ? db() : db;
    const resolvedTypename = typeof typename === 'function' ? typename() : typename;
    if (!resolvedTypename || !resolvedDb) {
      return undefined;
    }
    return { db: resolvedDb, typename: resolvedTypename };
  });

  // Store the current schema in a signal.
  const [schema, setSchema] = createSignal<T | undefined>(undefined);

  // Subscribe to registry changes.
  createEffect(() => {
    const r = resolved();
    if (!r) {
      // Keep previous value during transitions to prevent flickering.
      return;
    }

    const { db: resolvedDb, typename: resolvedTypename } = r;

    // Set initial value immediately.
    setSchema(
      () => Effect.runSync(resolvedDb.graph.registry.listTypes()).find((t) => Type.getTypename(t) === resolvedTypename) as T | undefined,
    );

    const unsubscribe = resolvedDb.graph.registry.changed.on(() => {
      setSchema(
        () => Effect.runSync(resolvedDb.graph.registry.listTypes()).find((t) => Type.getTypename(t) === resolvedTypename) as T | undefined,
      );
    });

    onCleanup(unsubscribe);
  });

  return schema;
};
