// packages/experimental/gem-globe/src/components/Globe.tsx
//
// Copyright 2018 DXOS.org
//

import * as d3 from 'd3';
import { type GeoProjection } from 'd3';
import React, {
  type PropsWithChildren,
  forwardRef,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from 'react';
import { useResizeDetector } from 'react-resize-detector';
import { type Topology } from 'topojson-specification';

import { Icon, type ThemedClassName, Toolbar, useDynamicRef } from '@dxos/react-ui';
import { mx } from '@dxos/react-ui-theme';

import { GlobeContextProvider, type GlobeContextProviderProps, type GlobeContextType, useGlobeContext } from '../hooks';
import {
  type Features,
  type Styles,
  type StyleSet,
  createLayers,
  renderLayers,
  timer,
  positionToRotation,
  geoToPosition,
} from '../util';

// https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute
const defaultStyles: Styles = {
  background: {
    fillStyle: '#111111',
  },

  water: {
    fillStyle: '#123E6A',
  },

  hex: {
    strokeStyle: 'green',
    fillStyle: 'gray',
    pointRadius: 1,
  },

  land: {
    fillStyle: '#032153',
  },

  line: {
    strokeStyle: '#111111',
  },

  point: {
    fillStyle: '#111111',
    strokeStyle: '#111111',
    strokeWidth: 1,
    pointRadius: 0.5,
  },
};

export type GlobeController = {
  canvas: HTMLCanvasElement;
  projection: GeoProjection;
} & Pick<GlobeContextType, 'scale' | 'translation' | 'rotation' | 'setScale' | 'setTranslation' | 'setRotation'>;

export type ProjectionType = 'orthographic' | 'mercator' | 'transverse-mercator';

const projectionMap: Record<ProjectionType, () => GeoProjection> = {
  orthographic: d3.geoOrthographic,
  mercator: d3.geoMercator,
  'transverse-mercator': d3.geoTransverseMercator,
};

const getProjection = (type: GlobeCanvasProps['projection'] = 'orthographic'): GeoProjection => {
  if (typeof type === 'string') {
    const constructor = projectionMap[type] ?? d3.geoOrthographic;
    return constructor();
  }

  return type ?? d3.geoOrthographic();
};

//
// Root
//

type GlobeRootProps = PropsWithChildren<ThemedClassName<GlobeContextProviderProps>>;

const GlobeRoot = ({ classNames, children, ...props }: GlobeRootProps) => {
  const { ref, width, height } = useResizeDetector<HTMLDivElement>();
  return (
    <div ref={ref} className={mx('relative flex grow overflow-hidden', classNames)}>
      <GlobeContextProvider size={{ width, height }} {...props}>
        {children}
      </GlobeContextProvider>
    </div>
  );
};

//
// Canvas
//

type GlobeCanvasProps = {
  projection?: ProjectionType | GeoProjection;
  topology?: Topology;
  features?: Features;
  styles?: StyleSet;
};

/**
 * Basic globe renderer.
 * https://github.com/topojson/world-atlas
 */
const GlobeCanvas = forwardRef<GlobeController, GlobeCanvasProps>(
  ({ projection: _projection, topology, features, styles = defaultStyles }, forwardRef) => {
    // Canvas.
    const [canvas, setCanvas] = useState<HTMLCanvasElement>(null);
    const canvasRef = (canvas: HTMLCanvasElement) => setCanvas(canvas);

    // Projection.
    const projection = useMemo(() => getProjection(_projection), [_projection]);

    // Layers.
    // TODO(burdon): Generate on the fly based on what is visible.
    const layers = useMemo(() => {
      return timer(() => createLayers(topology as Topology, features, styles));
    }, [topology, features, styles]);

    // State.
    const { size, center, scale, translation, rotation, setCenter, setScale, setTranslation, setRotation } =
      useGlobeContext();

    const scaleRef = useDynamicRef(scale);

    // Update rotation.
    useEffect(() => {
      if (center) {
        setScale(1);
        setRotation(positionToRotation(geoToPosition(center)));
      }
    }, [center]);

    // External controller.
    const zooming = useRef(false);
    useImperativeHandle<GlobeController, GlobeController>(
      forwardRef,
      () => {
        return {
          canvas,
          projection,
          center,
          get scale() {
            return scaleRef.current;
          },
          translation,
          rotation,
          setCenter,
          setScale: (s) => {
            if (typeof s === 'function') {
              const is = d3.interpolateNumber(scaleRef.current, s(scaleRef.current));
              // Stop easing if already zooming.
              d3.transition()
                .ease(zooming.current ? d3.easeLinear : d3.easeSinOut)
                .duration(200)
                .tween('scale', () => (t) => setScale(is(t)))
                .on('end', () => {
                  zooming.current = false;
                });
            } else {
              setScale(s);
            }
          },
          setTranslation,
          setRotation,
        };
      },
      [canvas],
    );

    // https://d3js.org/d3-geo/path#geoPath
    // https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext
    const generator = useMemo(
      () => canvas && projection && d3.geoPath(projection, canvas.getContext('2d', { alpha: false })),
      [canvas, projection],
    );

    // Render on change.
    useEffect(() => {
      if (canvas && projection) {
        timer(() => {
          // https://d3js.org/d3-geo/projection
          projection
            .scale((Math.min(size.width, size.height) / 2) * scale)
            .translate([size.width / 2 + (translation?.x ?? 0), size.height / 2 + (translation?.y ?? 0)])
            .rotate(rotation ?? [0, 0, 0]);

          renderLayers(generator, layers, scale);
        });
      }
    }, [generator, size, scale, translation, rotation, layers]);

    if (!size.width || !size.height) {
      return null;
    }

    return <canvas ref={canvasRef} width={size.width} height={size.height} />;
  },
);

//
// Controls
//

type GlobeControlsPosition = 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';

const controlPositions: Record<GlobeControlsPosition, string> = {
  'top-left': 'top-4 left-4',
  'top-right': 'top-4 right-4',
  'bottom-left': 'bottom-4 left-4',
  'bottom-right': 'bottom-4 right-4',
};

type GlobeControlAction = 'toggle' | 'start' | 'zoom-in' | 'zoom-out';

type GlobeControlsProps = ThemedClassName<{
  position?: GlobeControlsPosition;
  onAction?: (action: GlobeControlAction) => void;
}>;

const Button = ({ icon, onAction }: { icon: string; onAction?: () => void }) => (
  <Toolbar.Button classNames='min-bs-0 !p-1' variant='ghost' onClick={() => onAction?.()}>
    <Icon icon={icon} size={5} />
  </Toolbar.Button>
);

const GlobeZoomControls = ({ classNames, position = 'bottom-left', onAction }: GlobeControlsProps) => {
  // TODO(wittjosiah): This is a hack to get the theme to work. Gem isn't getting global theme context.
  return (
    <Toolbar.Root classNames={['z-10 absolute overflow-hidden !is-auto gap-0', controlPositions[position], classNames]}>
      <Button icon='ph--plus--regular' onAction={() => onAction?.('zoom-in')} />
      <Button icon='ph--minus--regular' onAction={() => onAction?.('zoom-out')} />
    </Toolbar.Root>
  );
};

const GlobeActionControls = ({ classNames, position = 'bottom-right', onAction }: GlobeControlsProps) => {
  // TODO(wittjosiah): This is a hack to get the theme to work. Gem isn't getting global theme context.
  return (
    <Toolbar.Root classNames={['z-10 absolute overflow-hidden !is-auto gap-0', controlPositions[position], classNames]}>
      <Button icon='ph--play--regular' onAction={() => onAction?.('start')} />
      <Button icon='ph--globe-hemisphere-west--regular' onAction={() => onAction?.('toggle')} />
    </Toolbar.Root>
  );
};

const GlobeDebug = ({ position = 'top-left' }: { position?: GlobeControlsPosition }) => {
  const { size, scale, translation, rotation } = useGlobeContext();
  return (
    <div
      className={mx(
        'z-10 absolute w-96 p-2 overflow-hidden border border-green-700 rounded',
        controlPositions[position],
      )}
    >
      <pre className='font-mono text-xs text-green-700'>
        {JSON.stringify({ size, scale, translation, rotation }, null, 2)}
      </pre>
    </div>
  );
};

const GlobePanel = ({
  position,
  classNames,
  children,
}: ThemedClassName<PropsWithChildren & { position?: GlobeControlsPosition }>) => {
  return <div className={mx('z-10 absolute overflow-hidden', controlPositions[position], classNames)}>{children}</div>;
};

export const Globe = {
  Root: GlobeRoot,
  Canvas: GlobeCanvas,
  ActionControls: GlobeActionControls,
  ZoomControls: GlobeZoomControls,
  Debug: GlobeDebug,
  Panel: GlobePanel,
};

export type { GlobeRootProps, GlobeCanvasProps, GlobeControlsProps, GlobeControlAction };

// packages/ui/solid-ui-geo/src/components/Globe/Globe.tsx
//
// Copyright 2025 DXOS.org
//

import { createResizeObserver } from '@solid-primitives/resize-observer';
import {
  type GeoProjection,
  easeLinear,
  easeSinOut,
  geoMercator,
  geoOrthographic,
  geoPath,
  geoTransverseMercator,
  interpolateNumber,
  transition,
} from 'd3';
import { type ControlPosition } from 'leaflet';
import { type Accessor, type JSX, type Setter, Show, createEffect, createMemo, createSignal } from 'solid-js';
import { type Topology } from 'topojson-specification';

import { GlobeContextProvider, type GlobeContextProviderProps, useGlobeContext } from '../../hooks';
import {
  type Features,
  type StyleSet,
  createLayers,
  geoToPosition,
  positionToRotation,
  renderLayers,
  timer,
} from '../../util';
import { ActionControls, type ControlProps, ZoomControls, controlPositions } from '../Toolbar';

/**
 * https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute
 */
const defaultStyles: Record<string, StyleSet> = {
  light: {
    background: {
      fillStyle: '#EEE',
    },

    water: {
      fillStyle: '#555',
    },

    land: {
      fillStyle: '#999',
    },

    line: {
      strokeStyle: 'darkred',
    },

    point: {
      fillStyle: '#111111',
      strokeStyle: '#111111',
      strokeWidth: 1,
      pointRadius: 0.5,
    },
  },
  dark: {
    background: {
      fillStyle: '#111111',
    },

    water: {
      fillStyle: '#123E6A',
    },

    land: {
      fillStyle: '#032153',
    },

    line: {
      strokeStyle: '#111111',
    },

    point: {
      fillStyle: '#111111',
      strokeStyle: '#111111',
      strokeWidth: 1,
      pointRadius: 0.5,
    },
  },
};

export type GlobeController = {
  canvas: HTMLCanvasElement;
  projection: GeoProjection;
  zoom: number;
  translation: Accessor<{ x: number; y: number } | undefined>;
  rotation: Accessor<[number, number, number] | undefined>;
  setZoom: (zoom: number | ((prev: number) => number)) => void;
  setTranslation: Setter<{ x: number; y: number } | undefined>;
  setRotation: (rotation: [number, number, number]) => void;
};

export type ProjectionType = 'orthographic' | 'mercator' | 'transverse-mercator';

const projectionMap: Record<ProjectionType, () => GeoProjection> = {
  orthographic: geoOrthographic,
  mercator: geoMercator,
  'transverse-mercator': geoTransverseMercator,
};

const getProjection = (type: GlobeCanvasProps['projection'] = 'orthographic'): GeoProjection => {
  if (typeof type === 'string') {
    const constructor = projectionMap[type] ?? geoOrthographic;
    return constructor();
  }

  return type ?? geoOrthographic();
};

//
// Root
//

type GlobeRootProps = {
  children: JSX.Element;
  class?: string;
} & Partial<GlobeContextProviderProps> &
  JSX.HTMLAttributes<HTMLDivElement>;

const GlobeRoot = (props: GlobeRootProps) => {
  let containerRef: HTMLDivElement | undefined;
  const [size, setSize] = createSignal({ width: 0, height: 0 });

  // Use @solid-primitives/resize-observer
  createResizeObserver(
    () => containerRef,
    ({ width, height }) => {
      setSize({ width, height });
    },
  );

  return (
    <div ref={containerRef} class={`relative flex grow overflow-hidden ${props.class ?? ''}`} {...props}>
      <GlobeContextProvider size={size()} {...props}>
        {props.children}
      </GlobeContextProvider>
    </div>
  );
};

//
// Canvas
//

type GlobeCanvasProps = {
  ref?: (controller: GlobeController) => void;
  projection?: ProjectionType | GeoProjection;
  topology?: Topology;
  features?: Features;
  styles?: StyleSet;
};

/**
 * Basic globe renderer.
 * https://github.com/topojson/world-atlas
 */

const GlobeCanvas = (props: GlobeCanvasProps) => {
  const themeMode = 'dark'; // TODO: Get from theme context
  const styles = createMemo(() => props.styles ?? defaultStyles[themeMode]);

  // Canvas.
  const [canvas, setCanvas] = createSignal<HTMLCanvasElement | null>(null);

  // Projection.
  const projection = createMemo(() => getProjection(props.projection));

  // Layers.
  const layers = createMemo(() => {
    return timer(() => createLayers(props.topology as Topology, props.features, styles()));
  });

  // State.
  const { size, center, zoom, translation, rotation, setCenter, setZoom, setTranslation, setRotation } =
    useGlobeContext();

  let zoomValue = zoom();
  let zooming = false;

  createEffect(() => {});

  // Update rotation.
  createEffect(() => {
    const c = center();
    if (c) {
      setZoom(1);
      setRotation(positionToRotation(geoToPosition(c)));
    }
  });

  // External controller.
  createEffect(() => {
    const canvasEl = canvas();
    if (canvasEl && props.ref) {
      const controller: GlobeController = {
        canvas: canvasEl,
        projection: projection(),
        get zoom() {
          return zoomValue;
        },
        translation,
        rotation,
        setZoom: (s) => {
          if (typeof s === 'function') {
            const is = interpolateNumber(zoomValue, s(zoomValue));
            // Stop easing if already zooming.
            transition()
              .ease(zooming ? easeLinear : easeSinOut)
              .duration(200)
              .tween('scale', () => (t) => {
                const newZoom = is(t);
                zoomValue = newZoom;
                setZoom(newZoom);
              })
              .on('end', () => {
                zooming = false;
              });
          } else {
            zoomValue = s;
            setZoom(s);
          }
        },
        setTranslation,
        setRotation,
      };
      props.ref(controller);
    }
  });

  // https://d3js.org/d3-geo/path#geoPath
  // https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext
  const generator = createMemo(() => {
    const canvasEl = canvas();
    const proj = projection();
    return canvasEl && proj && geoPath(proj, canvasEl.getContext('2d', { alpha: false }));
  });

  // Render on change.
  createEffect(() => {
    const canvasEl = canvas();
    const proj = projection();
    const gen = generator();
    const z = zoom();
    const t = translation();
    const r = rotation();
    const s = size();

    if (canvasEl && proj && gen) {
      timer(() => {
        // https://d3js.org/d3-geo/projection
        proj
          .scale((Math.min(s.width, s.height) / 2) * z)
          .translate([s.width / 2 + (t?.x ?? 0), s.height / 2 + (t?.y ?? 0)])
          .rotate(r ?? [0, 0, 0]);

        renderLayers(gen, layers(), z, styles());
      });
    }
  });

  return (
    <Show when={size().width > 0 && size().height > 0}>
      <canvas ref={setCanvas} width={size().width} height={size().height} />
    </Show>
  );
};

//
// Debug
//

const GlobeDebug = (props: { position?: ControlPosition }) => {
  const { size, zoom, translation, rotation } = useGlobeContext();
  return (
    <div
      class={`z-10 absolute w-96 p-2 overflow-hidden border border-green-700 rounded ${
        controlPositions[props.position ?? 'topleft']
      }`}
    >
      <pre class='font-mono text-xs text-green-700'>
        {JSON.stringify({ size, zoom: zoom(), translation: translation(), rotation: rotation() }, null, 2)}
      </pre>
    </div>
  );
};

//
// Panel
//

const GlobePanel = (props: { children: JSX.Element; position?: ControlPosition; class?: string }) => {
  return (
    <div class={`z-10 absolute overflow-hidden ${controlPositions[props.position ?? 'topleft']} ${props.class ?? ''}`}>
      {props.children}
    </div>
  );
};

//
// Controls
//

const CustomControl = (props: { children: JSX.Element; position: ControlPosition }) => {
  return <div class={`z-10 absolute overflow-hidden ${controlPositions[props.position]}`}>{props.children}</div>;
};

type GlobeControlProps = { position?: ControlPosition } & Pick<ControlProps, 'onAction'>;

const GlobeZoom = (props: GlobeControlProps) => (
  <CustomControl position={props.position ?? 'bottomleft'}>
    <ZoomControls onAction={props.onAction} />
  </CustomControl>
);

const GlobeAction = (props: GlobeControlProps) => (
  <CustomControl position={props.position ?? 'bottomright'}>
    <ActionControls onAction={props.onAction} />
  </CustomControl>
);

//
// Globe
//

export const Globe = {
  Root: GlobeRoot,
  Canvas: GlobeCanvas,
  Zoom: GlobeZoom,
  Action: GlobeAction,
  Debug: GlobeDebug,
  Panel: GlobePanel,
};

export type { GlobeRootProps, GlobeCanvasProps };
